version: "3.0"
services:
  kodenotes:
    build: .
    container_name: kodenotes
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    volumes:
      - ./logs:/go/logs

  postgres:
    image: postgres
    container_name: kodenotes-postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    user: postgres


