openapi: 3.0.1

info:
  title: KODE Notes
  description: Simple note taking REST API for KODE internship
  version: 0.1.0
  contact:
    email: rostomyan.tm@gmail.com

paths:
  /notes:
    get:
      description: Get all notes data
      tags:
        - notes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotesGet'

    post:
      description: Create new note. Checks text of note in Yandex Speller
      tags:
        - notes
      requestBody:
        description: Content of new note
        content:
          appication/json:
            schema:
              $ref: '#/components/schemas/NoteCreate'
      responses:
        "201":
          description: CREATED
          
components:
  schemas:
    NotesGet:
      type: object
      properties:
        notes:
          type: array
          items: 
            $ref: '#/components/schemas/NoteGet'
            
    NoteGet:
      type: object
      properties:
        id: 
          type: integer
        userId: 
          type: integer
        text: 
          type: string
        createdAt: 
          type: string
    
    NoteCreate:
      type: object
      properties:
        text:
          type: string
